### ISSUE TITLE
Nim not available as an option on https://ide.judge0.com

### ISSUE THREAD

**Issue by kaushalmodi** [judge0/ide#32]
Hello,

I was just going to try out the Emacs support on https://ide.judge0.com/, when I realized that Nim is one of the options in the langauge dropdown there.

The only way to access Nim Playground is by going to it subdomain: https://nim.ide.judge0.com/.

Is there a limitation that prevents Nim Playground from being accessed from https://ide.judge0.com/ as well?

**Comment by hermanzdosilovic** [comment]
Currently the only limitation is that Nim is not a part of official Judge0 API, but rather there exists a special release of Judge0 API that includes just Nim.

As a first step I can add Nim as an option to Judge0 IDE, but it will use API from https://nim.api.judge0.com instead of https://api.judge0.com.

I can then redirect https://nim.ide.judge0.com to https://ide.judge0.com.

**Comment by hermanzdosilovic** [comment]
Hi @kaushalmodi,

Nim is now available on Judge0 IDE (https://ide.judge0.com). Old site is still available at https://old.nim.ide.judge0.com but https://nim.ide.judge0.com redirects to Judge0 IDE.

**Comment by kaushalmodi** [comment]
Thanks for this quick followup!
